import { describe, expect, it } from "vitest";
import {
  DEFAULT_SETTINGS,
  SETTINGS_VERSION,
  normalizeCommentaryTuning,
  normalizeCommentaryVoice,
  reconcileSelectedDirectories,
  reconcileSettings,
  validateSettings,
} from "../../app/src/core/settings.js";

describe("settings", () => {
  it("uses versioned defaults and reconciles saved directory choices", () => {
    expect(DEFAULT_SETTINGS.version).toBe(SETTINGS_VERSION);
    expect(reconcileSelectedDirectories({
      mediaDirectories: [" albums ", "albums", "", "missing"],
      autoplayVideos: true,
      slideshowIntervalMs: 50,
    }, new Set(["albums"]))).toEqual({
      version: SETTINGS_VERSION,
      mediaDirectories: ["albums"],
      autoplayVideos: true,
      slideshowIntervalMs: 1000,
      tagSortOrder: DEFAULT_SETTINGS.tagSortOrder,
      captionSize: DEFAULT_SETTINGS.captionSize,
      captionTransparency: DEFAULT_SETTINGS.captionTransparency,
      captionDistance: DEFAULT_SETTINGS.captionDistance,
      admDefaultDepthIntensity: DEFAULT_SETTINGS.admDefaultDepthIntensity,
      admMaxResolution: DEFAULT_SETTINGS.admMaxResolution,
      autoGenerateDepthOnUpload: false,
      autoGenerateMaskOnUpload: false,
      commentaryVoice: "",
      commentaryPitch: 0,
      commentaryRate: 0,
    });
  });

  it("keeps upload generation toggles from saved settings", () => {
    const saved = reconcileSelectedDirectories({
      autoGenerateDepthOnUpload: true,
      autoGenerateMaskOnUpload: true,
    }, new Set());
    expect(saved.autoGenerateDepthOnUpload).toBe(true);
    expect(saved.autoGenerateMaskOnUpload).toBe(true);
  });

  it("keeps commentary TTS prefs and clamps tuning", () => {
    const saved = reconcileSettings({
      commentaryVoice: "en-US-Ava-neural",
      commentaryPitch: 12.7,
      commentaryRate: -200,
    });
    expect(saved.commentaryVoice).toBe("en-US-Ava-neural");
    expect(saved.commentaryPitch).toBe(13);
    expect(saved.commentaryRate).toBe(-50);

    expect(normalizeCommentaryVoice("a".repeat(600))).toHaveLength(500);
    expect(normalizeCommentaryTuning(Number.NaN, "commentaryPitch")).toBe(0);
    expect(normalizeCommentaryTuning(999, "commentaryRate")).toBe(50);

    expect(validateSettings({
      commentaryVoice: "ok",
      commentaryPitch: 51,
      commentaryRate: 0,
    }).valid).toBe(false);
    expect(validateSettings({
      commentaryVoice: "ok",
      commentaryPitch: 10,
      commentaryRate: -10,
    }).valid).toBe(true);
  });

});
